### ISSUE TITLE
Challenger Timer

### ISSUE THREAD

**Issue by janja-janja** [uonbi/codejam-platform#9]
@ProfNandaa Could we add a timer showing days:hours:mins:secs remaining to the challenge kick off? I think that would be awesome. Then when the day comes, it picks up emails of every plugged in Ninja and sends them an email notifying the kick off as well as open the challenge.

**Comment by profnandaa** [comment]
Hapo sawa, will be on it!

On Wed, Feb 25, 2015 at 5:01 PM, Denis Karanja notifications@github.com
wrote:

> @ProfNandaa https://github.com/ProfNandaa Could we add a timer showing
> day's remaining to the challenge kick off? I think that would be awesome.
> Then when the day comes, it picks up emails of every plugged in Ninja and
> sends them an email notifying the kick off as well as open the challenge.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/uonbi/codejam-platform/issues/9.

## 

_Nandaa Anthony,_
_Software Architect, Tutor & Mentor.__Google+: *http://gplus.to/profnandaa
*Blog: *www.nandaa.com http://nandaa.com
*Quick Links:_ sci.uonbi.ac.ke | www.deveint.com | www.gdgnairobi.info

**Comment by profnandaa** [comment]
Ye? Sema kuchangamka!

Sent from a not-so-smart device while on the move. Forgive the s/hand and
typpos ;-)

**Comment by profnandaa** [comment]
Hey @denisKaranja, however, you didn't need a whole model to do that, but rather a helper function...

**Comment by profnandaa** [comment]
But thanks for fixing this, all I did was code refactoring :) @denisKaranja

**Comment by janja-janja** [comment]
@profnandaa yeah man! It's been a crazy sweet week :)                                                                                                                                                                                                                                          From: Anthony NandaaSent: Tuesday, March 3, 2015 02:56To: uonbi/codejam-platformReply To: uonbi/codejam-platformCc: Denis KaranjaSubject: Re: [codejam-platform] Challenger Timer (#9)But thanks for fixing this, all I did was code refactoring :) @denisKaranja 

—Reply to this email directly or view it on GitHub.

**Comment by janja-janja** [comment]
‎@profnandaa noted. I dint want to interfere with the already done work :).                                                                                                                                                                                                                                         From: Anthony NandaaSent: Tuesday, March 3, 2015 02:50To: uonbi/codejam-platformReply To: uonbi/codejam-platformCc: Denis KaranjaSubject: Re: [codejam-platform] Challenger Timer (#9)Hey @denisKaranja, however, you didn't need a whole model to do that, but rather a helper function...

—Reply to this email directly or view it on GitHub.
